insert into t_admin (username,mdp) VALUES ('admin',sha1('123456'));
--donne de teste
insert into t_information (categorie,descri) VALUES ('prevention','Respecter les limites de taille pour les rassemblements à l intérieur et à l extérieur');
insert into t_information (categorie,descri) VALUES ('prevention','Suivez les conseils des autorités de santé publique de votre localité et adaptez votre comportement et vos habitudes en conséquence.');
insert into t_information (categorie,descri) VALUES ('prevention','Veiller au respect des gestes barrières et des mesures d ’ hygiène partout');
insert into t_information (categorie,descri) VALUES ('prevention','Utilisation des masques médicaux pour limiter la propagation');
insert into t_information (categorie,descri) VALUES ('prevention','Respecter les consignes du gouvernement');
insert into t_information (categorie,descri) VALUES ('symptome','Fièvre: 87,9 %');
insert into t_information (categorie,descri) VALUES ('symptome','Toux sèche: 67,7 %');
insert into t_information (categorie,descri) VALUES ('symptome','Fatigue: 38,1 %');
insert into t_information (categorie,descri) VALUES ('symptome','Expectorations: 33,4 %');
insert into t_information (categorie,descri) VALUES ('symptome','Expectorations: 33,4 %');
insert into t_information (categorie,descri) VALUES ('symptome','Diminution de sens du goût: 24 %');
insert into t_information (categorie,descri) VALUES ('symptome','Perte d odorat: 20 %');
insert into t_information (categorie,descri) VALUES ('symptome','Dyspnée: 18,6 %');
insert into t_information (categorie,descri) VALUES ('traitement','Les même que ceux de la grippe.');

insert into t_statistique (nouveaucas,gueris,deces,lieu) VALUES (50,0,0,2);
insert into t_statistique (nouveaucas,gueris,deces,lieu) VALUES (50,0,0,1);
insert into t_statistique (nouveaucas,gueris,deces,lieu) VALUES (10000,20,4,1);
insert into t_statistique (nouveaucas,gueris,deces,lieu) VALUES (154,2,10,2);

insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('DIRECT.Covid -19: le Danemark renonce à utiliser le vaccin Johnson & Johnson','Le Danemark a annoncé lundi 3 mai avoir renoncé à utiliser le vaccin Johnson & Johnson contre le Covid-19, à cause de possibles effets secondaires graves, notamment des cas de thromboses. Le pays avait été le premier d Europe a abandonner le vaccin d AstraZeneca en avril dernier. La non-utilisation de ces deux vaccins, pourtant autorisés par l Agence européenne du médicament et l OMS, devrait retarder de quatre semaines la campagne de vaccination danoise. Selon le dernier pointage, 11,5% des 5,8 millions de Danois sont entièrement vaccinés et 23,4% ont reçu une première injection. Suivez notre direct.',NOW(),1);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Flambée des cas de Covid -19 en Inde: un élan de solidarité mondial pour venir en aide au pays','Des respirateurs artificiels, des ventilateurs, mais aussi des masques, du gel hydroalcoolique et, surtout, « de l ’ oxygène sous toutes ses formes », comme l ’ indique Emmanuel Baron, médecin épidémiologiste à Médecins sans frontières (MSF).Voilà le matériel médical et les fournitures essentielles réclamées par l ’ Etat indien qui ont commencé à arriver ce mardi dans les hôpitaux du pays en provenance du Royaume - Uni.Les cargaisons devraient continuer à approvisionner le territoire indien dans les prochains jours, par fret aérien ou maritime en provenance du monde entier.',NOW(),1);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Covid-19. La situation en Inde est «?plus que déchirante?», les États-Unis et la France viennent à l aide','Pour répondre à la situation sanitaire « ? plus que déchirante ? » en Inde, les premiers cargos de matériel médical britanniques arrivent dans le pays ce mardi matin.Les États - Unis et la France ont également promis de l aide.',NOW(),1);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Nouveau record mondial de contaminations au Covid -19 en Inde','Face à la poussée spectaculaire de l épidémie de coronavirus en Inde, plusieurs pays dont ceux de l UE, le Royaume - Uni et les Etats - Unis ont promis leur aide.L Inde a enregistré dimanche un record de près de 350 000 personnes contaminées en une seule journée.',NOW(),1);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Transport aérien: / Covid -19: l IATA revoit en baisse sa prévision de trafic pour 2021','En raison du retard lié à la vaccination contre la Covid -19 et de l aversion au risque des Etats qui retardent la réouverture des liaisons, le trafic aérien se remettra plus lentement que prévu, a indiqué l Association internationale du transport aérien (IATA).',NOW(),1);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Ce qu il faut savoir sur l artemisia, base d un remède controversé contre le Covid-19 créé à Madagascar','Un breuvage destiné à "changer l Histoire".Le président de Madagascar, Andry Rajoelina, attire regards et interrogations avec un remède local baptisé "Covid Organics", une tisane à base d Artemisia et de plantes traditionnelles malgaches, censée guérir du Covid -19.Commercialisée sous différentes formes et élaborée par l IMRA, l Institut malgache de recherches appliquées, la potion est vendue partout sur l île et distribuée aux plus défavorisés.Sa consommation conditionne même le retour à l école des élèves malgaches.La Guinée Equatoriale, le Niger, la Tanzanie ou encore les Comores ont déjà réceptionné des cartons de tisane "Covid Organics" pour leurs malades.',NOW(),2);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('A Madagascar, des hôpitaux sous-équipés et débordés face à l afflux des malades du Covid-19','Le pays fait face à une vague meurtrière de coronavirus, due au variant sud - africain, avec près de 10 000 cas et 200 décès en un mois, selon les chiffres officiels.',NOW(),2);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Covid -19: Madagascar reconduit l état d urgence sanitaire pour deux semaines','Le président de la République Andry Rajoelina s est exprimé à la télévision et à la radio nationale dimanche soir 18 avril pour annoncer de nouvelles mesures plus strictes pour lutter contre la propagation du Covid -19 qui sature les hôpitaux et les centres de traitement ouverts spécialement pour les malades du coronavirus.L état d urgence sanitaire est reconduit pour les deux prochaines semaines.',NOW(),2);
insert into t_actualite (titre,evenement,dateevent,lieu) VALUES ('Madagascar: des écoles transformées en hôpitaux pour les malades de la Covid -19','Certains hôtels de la capitale sont aussi utilisés pour héberger des patients, alors que le pays fait face à la deuxième vague de Covid et à son variant sud - africain, réputé plus agressif.',NOW(),2);